[build]
  command = "SKIP_TYPE_CHECK=1 npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_USE_YARN = "false"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"
  SKIP_TYPE_CHECK = "1"

# Improve build performance
[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/@neondatabase/serverless/**"]

# Handle API routes and SPA behavior
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "frame-ancestors 'none'"

# Handle Next.js dynamic routes and API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Handle PWA routes
[[redirects]]
  from = "/service-worker.js"
  to = "/service-worker.js"
  status = 200

# Fallback SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
